name: JoinLogger
version: 1.0
author: AvhiDh
main: com.github.AvhiDh.JoinLogger
api-version: '1.19'
commands:
  jl:
    description: JoinLogger Admin Commands
    usage: /jl
    permission: JoinLogger.Admin