name: JoinLogger
version: 1.0
author: AvhiDh
main: com.github.AvhiDh.JoinLogger
api-version: '1.19'
commands:
  jlreload:
    description: Reload JoinLogger Config
    usage: /jlreload
    permission: DeathSpot.Reload